spring:
  application:
    name: Permissions # Name of your Spring Boot application
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect # Specify the MySQL dialect here
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Permissions?serverTimezone=UTC
    username: root
    password:

logging:
  level:
    org.springframework.security: TRACE